extends CharacterBody2D
## Player: movement, state-driven animation, and the work day's energy.
## Energy here is the CHARACTER's, separate from the station's — see docs/Mecanicas-Scraptronaut.md
## and docs/arquitetura/trabalho-energia-e-dia.md. Only construction work spends it.

signal energy_changed(energy: float, max_energy: float)

const SPEED: float = 230.0
const ACCELERATION: float = 2200.0
const FRICTION: float = 2600.0

## One work day, same unit as StationMap.WORK_PER_CELL — see docs/arquitetura/trabalho-energia-e-dia.md.
const MAX_ENERGY: float = 100.0

## Below this the bar turns red; doesn't block anything.
const LOW_ENERGY: float = 25.0

enum State { IDLE, WALKING, WORKING, SLEEPING }

## Single 4x8 sheet: one row per direction, four walk frames each.
## Generated by tools/gerar_miro_8dir.py — see docs/arquitetura/personagem-e-animacao.md.
const WALK_TEXTURE: Texture2D = preload("res://assets/sprites/miro_8dir.png")

## The other three come from the walk sheet, via tools/gerar_miro_estados.py.
const IDLE_TEXTURE: Texture2D = preload("res://assets/sprites/miro_idle.png")
const WORK_TEXTURE: Texture2D = preload("res://assets/sprites/miro_working.png")
const SLEEP_TEXTURE: Texture2D = preload("res://assets/sprites/miro_sleeping.png")

## Sheet rows, in drawn order — see docs/arquitetura/personagem-e-animacao.md.
enum Facing {
	DOWN,
	RIGHT,
	UP,
	LEFT,
	DOWN_RIGHT,
	DOWN_LEFT,
	UP_RIGHT,
	UP_LEFT,
}

## Movement-angle octant -> sheet row. See docs/arquitetura/personagem-e-animacao.md.
const FACING_BY_OCTANT: Array[Facing] = [
	Facing.RIGHT,
	Facing.DOWN_RIGHT,
	Facing.DOWN,
	Facing.DOWN_LEFT,
	Facing.LEFT,
	Facing.UP_LEFT,
	Facing.UP,
	Facing.UP_RIGHT,
]

## Half the square's side (cosine of 45 degrees); written by hand — not a constant expression in GDScript.
const DIAGONAL: float = 0.70710678

## Unit heading for each facing — the inverse of FACING_BY_OCTANT.
const HEADING_BY_FACING: Array[Vector2] = [
	Vector2(0, 1),
	Vector2(1, 0),
	Vector2(0, -1),
	Vector2(-1, 0),
	Vector2(DIAGONAL, DIAGONAL),
	Vector2(-DIAGONAL, DIAGONAL),
	Vector2(DIAGONAL, -DIAGONAL),
	Vector2(-DIAGONAL, -DIAGONAL),
]

## Sprite offset: feet at the cell's base, head centered. See tools/gerar_objetos.py for the math.
const SPRITE_OFFSET: Vector2 = Vector2(0, -46)

## The work sheet's cell is 10px taller, for the raised pickaxe; feet stay put, only the center moves.
const WORK_OFFSET: Vector2 = Vector2(0, -51)

const FRAMES: int = 4

## The generator already recorded the cycle in the right order (contact, pass, contact, pass).
const INITIAL_FRAME: int = 0

## Columns where the foot touches ground — where the footstep sound fires. See
## tools/gerar_miro_8dir.py and docs/arquitetura/som.md.
const CONTACT_FRAMES: Array[int] = [0, 2]

## Pickaxe-impact column — where the hammer-hit sound fires. See tools/gerar_miro_estados.py.
const IMPACT_FRAME: int = 2

## Animation is driven by distance traveled, not the clock, so slowing down slows the stride for free.
## Measured by the generator in side view. See docs/arquitetura/personagem-e-animacao.md.
const WALK_STRIDE_PIXELS: float = 84.2

## How much the animation is stretched beyond the measured stride. See docs/arquitetura/personagem-e-animacao.md.
const WALK_STRETCH: float = 1.4

## Cycle duration, in seconds, for the non-walking states. See docs/arquitetura/personagem-e-animacao.md.
const IDLE_CYCLE: float = 2.6
const WORK_CYCLE: float = 0.8
const SLEEP_CYCLE: float = 4.2

## Below this speed counts as stopped, so the sprite doesn't flicker as friction zeroes it out.
const IDLE_SPEED_THRESHOLD: float = 8.0

## Mouse-wheel zoom range and step for the game camera. Same step as build mode's, on
## purpose — different sensitivities for the same wheel gesture would stand out immediately.
## See docs/arquitetura/interface-e-camera.md.
const MIN_ZOOM: float = 0.26
const MAX_ZOOM: float = 0.62
const ZOOM_STEP: float = 1.12

@onready var _sprite: Sprite2D = $Sprite2D
@onready var _camera: Camera2D = $Camera2D

var energy: float = MAX_ENERGY

var _state: State = State.IDLE
var _facing: Facing = Facing.DOWN
var _step: float = 0.0

## Last column drawn, for sound only — see _play_sound().
var _drawn_frame: int = -1

## Locked in build mode: WASD moves the camera there, not the character.
var _locked: bool = false


func lock(value: bool) -> void:
	_locked = value
	if value:
		velocity = Vector2.ZERO
		_change_state(State.IDLE)


## Unit vector the character is facing — the drawn facing, not velocity. Used to pick
## which site the pickaxe hits (see StationMap.nearby_site).
func heading() -> Vector2:
	return HEADING_BY_FACING[int(_facing)]


## Enters the hammer-hit pose, facing the work point. Called every frame while held.
func work_toward(global_target: Vector2) -> void:
	var toward: Vector2 = global_target - global_position
	if toward.length() > 1.0:
		_update_facing(toward.normalized())
	velocity = Vector2.ZERO
	_change_state(State.WORKING)


func stop_working() -> void:
	if _state == State.WORKING:
		_change_state(State.IDLE)


## Lies down on the bed. Position comes from Bed.sleep_point().
func lie_down(pos: Vector2) -> void:
	global_position = pos
	velocity = Vector2.ZERO
	_facing = Facing.DOWN
	_change_state(State.SLEEPING)


func stand_up(pos: Vector2) -> void:
	global_position = pos
	_change_state(State.IDLE)


func is_sleeping() -> bool:
	return _state == State.SLEEPING


## Spends up to `amount` of energy and returns what was actually spent.
func spend_energy(amount: float) -> float:
	var spent: float = minf(amount, energy)
	if spent <= 0.0:
		return 0.0
	energy -= spent
	energy_changed.emit(energy, MAX_ENERGY)
	return spent


## Whether the bar should read as low. A method, not a bare constant read, because
## callers without static typing (get_node by name) can't reach a const via get().
func is_low_energy() -> bool:
	return energy <= LOW_ENERGY


func rest() -> void:
	energy = MAX_ENERGY
	energy_changed.emit(energy, MAX_ENERGY)


func _ready() -> void:
	_apply_sheet()
	_draw_frame(INITIAL_FRAME)
	energy_changed.emit(energy, MAX_ENERGY)


func _process(delta: float) -> void:
	# Walking is driven by distance in _physics_process; the other three by the clock.
	match _state:
		State.IDLE:
			_advance_cycle(delta, IDLE_CYCLE)
		State.WORKING:
			_advance_cycle(delta, WORK_CYCLE)
		State.SLEEPING:
			_advance_cycle(delta, SLEEP_CYCLE)
		_:
			pass


func _physics_process(delta: float) -> void:
	if _locked or _state == State.SLEEPING or _state == State.WORKING:
		return
	var direction: Vector2 = _read_direction()
	if direction == Vector2.ZERO:
		velocity = velocity.move_toward(Vector2.ZERO, FRICTION * delta)
	else:
		velocity = velocity.move_toward(direction * SPEED, ACCELERATION * delta)
		_update_facing(direction)
	move_and_slide()

	var moving: bool = velocity.length() > IDLE_SPEED_THRESHOLD
	_change_state(State.WALKING if moving else State.IDLE)
	if _state == State.WALKING:
		_advance_step(delta)


## Mouse wheel zooms the game camera in and out. Lives here, not in build mode's node,
## because the camera is the player's — build mode consumes the wheel first as a later
## sibling in the tree, so this never sees it while build mode is open.
func _unhandled_input(event: InputEvent) -> void:
	if _locked or not (event is InputEventMouseButton):
		return
	var button := event as InputEventMouseButton
	if not button.pressed:
		return
	var factor: float = 0.0
	if button.button_index == MOUSE_BUTTON_WHEEL_UP:
		factor = ZOOM_STEP
	elif button.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		factor = 1.0 / ZOOM_STEP
	if factor == 0.0:
		return
	var new_zoom: float = clampf(_camera.zoom.x * factor, MIN_ZOOM, MAX_ZOOM)
	_camera.zoom = Vector2(new_zoom, new_zoom)
	get_viewport().set_input_as_handled()


func _read_direction() -> Vector2:
	var direction := Vector2(
		Input.get_axis(&"ui_left", &"ui_right"),
		Input.get_axis(&"ui_up", &"ui_down")
	)
	if Input.is_physical_key_pressed(KEY_A):
		direction.x -= 1.0
	if Input.is_physical_key_pressed(KEY_D):
		direction.x += 1.0
	if Input.is_physical_key_pressed(KEY_W):
		direction.y -= 1.0
	if Input.is_physical_key_pressed(KEY_S):
		direction.y += 1.0
	return direction.limit_length(1.0)


# --- Sprite state switching --------------------------------------------------

func _change_state(new_state: State) -> void:
	if new_state == _state:
		return
	_state = new_state
	_step = 0.0
	_apply_sheet()
	_draw_frame(INITIAL_FRAME)


## Sheet, grid and offset for the current state. See docs/arquitetura/personagem-e-animacao.md.
func _apply_sheet() -> void:
	match _state:
		State.WALKING:
			_sprite.texture = WALK_TEXTURE
			_sprite.offset = SPRITE_OFFSET
			_sprite.vframes = Facing.size()
		State.WORKING:
			_sprite.texture = WORK_TEXTURE
			_sprite.offset = WORK_OFFSET
			_sprite.vframes = Facing.size()
		State.SLEEPING:
			# Only one lying pose: seen from above, lying face-up is the only option here.
			_sprite.texture = SLEEP_TEXTURE
			_sprite.offset = SPRITE_OFFSET
			_sprite.vframes = 1
		_:
			_sprite.texture = IDLE_TEXTURE
			_sprite.offset = SPRITE_OFFSET
			_sprite.vframes = Facing.size()
	_sprite.hframes = FRAMES
	# All eight directions are drawn; nothing is mirrored.
	_sprite.flip_h = false


func _update_facing(direction: Vector2) -> void:
	var previous: Facing = _facing
	# posmod, not %: angle() returns -PI..PI, so upward movement gives a negative octant.
	var octant: int = posmod(roundi(direction.angle() / (TAU / 8.0)), 8)
	_facing = FACING_BY_OCTANT[octant]

	# Turning mid-stride doesn't restart the cycle: every row has the same frame count.
	if _facing != previous:
		_draw_frame(int(_step))


# --- Cycles ------------------------------------------------------------------

func _advance_step(delta: float) -> void:
	var cycle: float = WALK_STRIDE_PIXELS * WALK_STRETCH
	var distance: float = velocity.length() * delta
	var step_amount: float = distance / cycle * FRAMES
	_step = fmod(_step + step_amount, float(FRAMES))
	_draw_frame(int(_step))


func _advance_cycle(delta: float, seconds: float) -> void:
	_step = fmod(_step + delta / seconds * FRAMES, float(FRAMES))
	_draw_frame(int(_step))


func _draw_frame(column: int) -> void:
	var row: int = 0 if _state == State.SLEEPING else int(_facing)
	_sprite.frame_coords = Vector2i(column, row)
	if column != _drawn_frame:
		_drawn_frame = column
		_play_sound(column)


## Plays the sound for the frame that just started, if the current state has one.
## Triggered by the COLUMN changing, not a separate timer — see docs/arquitetura/som.md.
func _play_sound(column: int) -> void:
	match _state:
		State.WALKING:
			if column in CONTACT_FRAMES:
				Sound.footstep()
		State.WORKING:
			if column == IMPACT_FRAME:
				Sound.hammer_hit()
		_:
			pass
